

- [X] deep fillInDefaults
- relations, by passing in other models and how they relate
  #+BEGIN_SRC typescript
    useModel({
      type,
      schema: obj({ id: int(), otherModelId: int() }),
      relations: {
      // pass it the filter, to load by
        useOtherModel: (content) => ({ id: content.otherModelId })
      }
    }, collectionName);
  #+END_SRC
  Some schema that specifies the other model directly in the type?
  could use derived?
  #+BEGIN_SRC typescript
    useModel({
      type,
      schema: obj({ id: int(), otherModel: otherModelSchema.reference() }),
      relations: {
      // pass it the filter, to load by
        useOtherModel: (content) => ({ id: content.otherModelId })
      }
    }, collectionName);
  #+END_SRC
  Or just the id and the relations object takes as key where the other
  model will be loaded to? How exactly would the specification of the
  other models use function and how the keys are related look like?
  #+BEGIN_SRC typescript
    useModel({
      type,
      schema: obj({ id: int(), otherModelId: int() }),
      relations: {
      // pass it the filter, to load by
        otherModel: (content) => useOtherModel.load({ id: content.otherModelId })
      }
    }, collectionName);
    const model = /*...*/
    await model.loadRelation("otherModel")
    model.otherModel.xy = 3;
  #+END_SRC
  - Use these relations to allow @apparts/model-api to return what has
    to be deleted cascadingly
  - Inner join with array_agg for retrieving relations? https://stackoverflow.com/a/41685553
- export ManyModel and extend it (CustomModel)
  - pass it into makeModel
  - +OneModel derives CustomModel+
  - +makeModel returns OneModel, NoneModel+
- storeOrUpdate function
- pass Context obj instead of dbs obj?
  - Context = { dbs: GenericDBS, log, ...}
- Remove all console.logs
- Improve interface of makeModel
- Store derived values? (If you only update data through the model,
  and the derived values are computed on change/store, they will
  always be correct)
  - Advantage: You can sort and filter by them
  - Disadvantage: might not work for everything. I.e. if derived value
    is calculated based on other resources, too
- Idea based on .net ef: Have a request-dependent context that knows
  what has been loaded, changed(?)

*TODOS:*
- [X] transform anyModel to TS
- [X] transform manyModel to TS
- [X] type of public? how to do? (return type of getPublic)
- [ ] +how to do oneModel inheritance?+


Sandwich model:

- anyModel -> manyModel [-> customModel] -> oneModel [-> customOneModel]
- anyModel -> customModel -> manyModel
                          -> oneModel
  - does not make sense, as you cannot overwrite anything on manyModel


- different call structure in one/manyModel:
  - getPublic
  - getWithDerived



* Repository

DbContextRepository added to request Context
- can cache stuff
- new one on every request
- function can be passed to model-api that extracts a Repository from
  Context so that any model with any data source can be used in model-api
- Model Factory for creating/manipulating model objects
  - new
  - newWDefaults ?
  - checkType
  - getPublic
  - getWithDefaults
  - hasValidKeys
  - getCollection
  - getSchema
  - custom functions?
#+BEGIN_SRC typescript
// creation
const userFactory = makeFactory({ schema, collection? });

// middleware
req.context.dbRepo = new DbContextRepository(dbs);

// usage
const user = userFactory.newWDefaults({...})
await userFactory(repo).store(user)

// transaction
dbs.transaction(dbs => {
  transactionRepo = new DbContextRepository(dbs);
});
#+END_SRC



Repo inherits from Manager (formerly factory)
#+BEGIN_SRC js
class GenericRepository extends Manager<T> {
  constructur(manager: Manager<T>) {
    this._manager = manager;
  }
}

class DbRepository extends GenericRepository {
  constructur(manager: Manager) {
    super(manager);
  }
  initialize(queriable) {
    this._queriable = queriable;
  }
  load() {
    // ...
  }
  // ...
}


const user = userManager({..}); // or
const user = userManager.new({..});

const user = await userManager.repo(dbs).load({...});
await userManager(user).repo(dbs).store(); // or
await userManager.repo(dbs).store(user);

const userRepo = userManager.repo(dbs) // returns DbRepository extends EntityManager
// hence userRepo has all the functions a userManager has:
const newUser = userRepo.new({ ... });

#+END_SRC


* Loading Relations:

- prevent the situation we have on our .net code base, where we can
  load relations but cannot properly type that they are loaded. Issue
  is: Either you do not use these relations (which would be a shame)
  or you don't know how to pass them to functions while also making
  sure, that they receive an entity that is loaded with the subentities:
  #+BEGIN_SRC csharp
    public AFunction(Table table) {
      table.Configuration.Location.Name = "Renamed location"
    }

    var table = _context.Table
        .Where(e => e.Id == 1932)
        .Include(e => e.Configuration)
        .ThenInclude(e => e.ConnectedSystem)
        .ThenInclude(e => e.Location)
        .FirstOrDefault();
    AFunction(table) // ok

    var table2 = _context.Table
        .Where(e => e.Id == 1932);
    AFunction(table2) // error
  #+END_SRC

- One Option: Use Lazy loading with js getters and setters. They can be
  used on plain objects.
  #+BEGIN_SRC js
    const a = {
      test: 3
    };
    a.__defineGetter__("test", () => 4)
    a.test // -> 4 
  #+END_SRC
  - Nope. Can't do that. If we need to fetch in here, it would be
    async. Then the getter could only return a Promise. That sucks
- Easiest option: Just don't be too clever and just return new
  entities
  #+BEGIN_SRC js
    const user = userFactory.load({...});

    const posts = await userFactory(repo).getRelation("posts");
    // modify posts
    postsFactory(repo).store(posts);
  #+END_SRC



Optimistic concurrency check (inspired by entity framework):
- Only one column:
  - One column X has a "ConcurrencyCheck" Flag
  - Do your (side effect free) calculations, then, when done,
    #+BEGIN_SRC sql
    UPDATE <table with data> WHERE <where clause>
       AND X = <Value of X when we started the calculation>;
    #+END_SRC
    - If 1 row is updated, all ok
    - If 0 rows updated: Concurrency failure
      + Do everything again (get data, process data, update)
      + Reject change
  - Also for =DELETE=
- Whole table:
  - Add a column "rowVersion" that has an ever increasing number
  - Each change increases the number
  - "rowVersion" is used as as if it had a "ConcurrencyCheck" Flag
  - Only really viable, if all changing requests update the
    "rowVersion" column, hence support from model needed
